[package]
authors = ["RENEC Maintainers <dev@remitano.com>"]
edition = "2021"
name = "renec-install"
description = "The RENEC cluster software installer"
version = "1.13.6"
repository = "https://github.com/remitano/renec"
license = "Apache-2.0"
homepage = "https://remitano.com/"
documentation = "https://docs.rs/renec-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.3"
bzip2 = "0.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.15.0"
crossbeam-channel = "0.5"
ctrlc = { version = "3.2.1", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
nix = "0.23.1"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = "1.0.6"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
solana-clap-utils = { path = "../clap-utils", version = "=1.13.6" }
solana-client = { path = "../client", version = "=1.13.6" }
solana-config-program = { path = "../programs/config", version = "=1.13.6" }
solana-logger = { path = "../logger", version = "=1.13.6" }
solana-sdk = { path = "../sdk", version = "=1.13.6" }
solana-version = { path = "../version", version = "=1.13.6" }
tar = "0.4.38"
tempfile = "3.3.0"
url = "2.2.2"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.10"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
